MERGE EPR_header AS target
USING (SELECT ? AS PCC_Cd, ? AS User_Id, ? AS Account_Cd, ? AS Office_Cd, ? AS Agent_Sine, ? AS Active_Ind, ? AS Access_Method_Txt, ? AS Agent_Last_Nm, ? AS Agent_Initial_Nm, ? AS Home_Office_Cd, ? AS Home_City_Txt, ? AS Last_Sign_in_Dt, ? AS PIN_Set_Ind, ? AS Password_Set_Ind, ? AS PIV_Questions_Ind, ? AS Duty_0_Cd_Ind, ? AS Duty_1_Cd_Ind, ? AS Duty_2_Cd_Ind, ? AS Duty_3_Cd_Ind, ? AS Duty_4_Cd_Ind, ? AS Duty_5_Cd_Ind, ? AS Duty_6_Cd_Ind, ? AS Duty_7_Cd_Ind, ? AS Duty_8_Cd_Ind, ? AS Duty_9_Cd_Ind, ? AS Duty_Hash_Cd_Ind, ? AS Duty_Dash_Cd_Ind, ? AS Duty_Star_Cd_Ind, ? AS Duty_Slash_Cd_Ind, ? AS Duty_Mesh_Cd_Ind, ? AS Duty_0_Temp_Cd_Ind, ? AS Duty_1_Temp_Cd_Ind, ? AS Duty_2_Temp_Cd_Ind, ? AS Duty_3_Temp_Cd_Ind, ? AS Duty_4_Temp_Cd_Ind, ? AS Duty_5_Temp_Cd_Ind, ? AS Duty_6_Temp_Cd_Ind, ? AS Duty_7_Temp_Cd_Ind, ? AS Duty_8_Temp_Cd_Ind, ? AS Duty_9_Temp_Cd_Ind, ? AS Duty_Hash_Temp_Cd_Ind, ? AS Duty_Dash_Temp_Cd_Ind, ? AS Duty_Star_Temp_Cd_Ind, ? AS Duty_Slash_Temp_Cd_Ind, ? AS Duty_Mesh_Temp_Cd_Ind, ? AS SCR_Group, ? AS RecordStatus, ? AS Keyword_Changed, ? AS EffectiveDate, ? AS MCP_Partition_Code, ? AS Default_Ticketing_Carrier, ? AS Station_Code) AS source
ON (source.PCC_Cd = target.PCC_Cd) AND (source.User_Id = target.User_Id) AND (source.EffectiveDate = target.EffectiveDate)
WHEN MATCHED THEN UPDATE SET
target.Account_Cd = source.Account_Cd,
target.Office_Cd = source.Office_Cd,
target.Agent_Sine = source.Agent_Sine,
target.Active_Ind = source.Active_Ind,
target.Access_Method_Txt = source.Access_Method_Txt,
target.Agent_Last_Nm = source.Agent_Last_Nm,
target.Agent_Initial_Nm = source.Agent_Initial_Nm,
target.Home_Office_Cd = source.Home_Office_Cd,
target.Home_City_Txt = source.Home_City_Txt,
target.Last_Sign_in_Dt = source.Last_Sign_in_Dt,
target.PIN_Set_Ind = source.PIN_Set_Ind,
target.Password_Set_Ind = source.Password_Set_Ind,
target.PIV_Questions_Ind = source.PIV_Questions_Ind,
target.Duty_0_Cd_Ind = source.Duty_0_Cd_Ind,
target.Duty_1_Cd_Ind = source.Duty_1_Cd_Ind,
target.Duty_2_Cd_Ind = source.Duty_2_Cd_Ind,
target.Duty_3_Cd_Ind = source.Duty_3_Cd_Ind,
target.Duty_4_Cd_Ind = source.Duty_4_Cd_Ind,
target.Duty_5_Cd_Ind = source.Duty_5_Cd_Ind,
target.Duty_6_Cd_Ind = source.Duty_6_Cd_Ind,
target.Duty_7_Cd_Ind = source.Duty_7_Cd_Ind,
target.Duty_8_Cd_Ind = source.Duty_8_Cd_Ind,
target.Duty_9_Cd_Ind = source.Duty_9_Cd_Ind,
target.Duty_Hash_Cd_Ind = source.Duty_Hash_Cd_Ind,
target.Duty_Dash_Cd_Ind = source.Duty_Dash_Cd_Ind,
target.Duty_Star_Cd_Ind = source.Duty_Star_Cd_Ind,
target.Duty_Slash_Cd_Ind = source.Duty_Slash_Cd_Ind,
target.Duty_Mesh_Cd_Ind = source.Duty_Mesh_Cd_Ind,
target.Duty_0_Temp_Cd_Ind = source.Duty_0_Temp_Cd_Ind,
target.Duty_1_Temp_Cd_Ind = source.Duty_1_Temp_Cd_Ind,
target.Duty_2_Temp_Cd_Ind = source.Duty_2_Temp_Cd_Ind,
target.Duty_3_Temp_Cd_Ind = source.Duty_3_Temp_Cd_Ind,
target.Duty_4_Temp_Cd_Ind = source.Duty_4_Temp_Cd_Ind,
target.Duty_5_Temp_Cd_Ind = source.Duty_5_Temp_Cd_Ind,
target.Duty_6_Temp_Cd_Ind = source.Duty_6_Temp_Cd_Ind,
target.Duty_7_Temp_Cd_Ind = source.Duty_7_Temp_Cd_Ind,
target.Duty_8_Temp_Cd_Ind = source.Duty_8_Temp_Cd_Ind,
target.Duty_9_Temp_Cd_Ind = source.Duty_9_Temp_Cd_Ind,
target.Duty_Hash_Temp_Cd_Ind = source.Duty_Hash_Temp_Cd_Ind,
target.Duty_Dash_Temp_Cd_Ind = source.Duty_Dash_Temp_Cd_Ind,
target.Duty_Star_Temp_Cd_Ind = source.Duty_Star_Temp_Cd_Ind,
target.Duty_Slash_Temp_Cd_Ind = source.Duty_Slash_Temp_Cd_Ind,
target.Duty_Mesh_Temp_Cd_Ind = source.Duty_Mesh_Temp_Cd_Ind,
target.SCR_Group = source.SCR_Group,
target.RecordStatus = source.RecordStatus,
target.Keyword_Changed = source.Keyword_Changed,
target.MCP_Partition_Code = source.MCP_Partition_Code,
target.Default_Ticketing_Carrier = source.Default_Ticketing_Carrier,
target.Station_Code = source.Station_Code
WHEN NOT MATCHED THEN INSERT (PCC_Cd, User_Id, Account_Cd, Office_Cd, Agent_Sine, Active_Ind, Access_Method_Txt, Agent_Last_Nm, Agent_Initial_Nm, Home_Office_Cd, Home_City_Txt, Last_Sign_in_Dt, PIN_Set_Ind, Password_Set_Ind, PIV_Questions_Ind, Duty_0_Cd_Ind, Duty_1_Cd_Ind, Duty_2_Cd_Ind, Duty_3_Cd_Ind, Duty_4_Cd_Ind, Duty_5_Cd_Ind, Duty_6_Cd_Ind, Duty_7_Cd_Ind, Duty_8_Cd_Ind, Duty_9_Cd_Ind, Duty_Hash_Cd_Ind, Duty_Dash_Cd_Ind, Duty_Star_Cd_Ind, Duty_Slash_Cd_Ind, Duty_Mesh_Cd_Ind, Duty_0_Temp_Cd_Ind, Duty_1_Temp_Cd_Ind, Duty_2_Temp_Cd_Ind, Duty_3_Temp_Cd_Ind, Duty_4_Temp_Cd_Ind, Duty_5_Temp_Cd_Ind, Duty_6_Temp_Cd_Ind, Duty_7_Temp_Cd_Ind, Duty_8_Temp_Cd_Ind, Duty_9_Temp_Cd_Ind, Duty_Hash_Temp_Cd_Ind, Duty_Dash_Temp_Cd_Ind, Duty_Star_Temp_Cd_Ind, Duty_Slash_Temp_Cd_Ind, Duty_Mesh_Temp_Cd_Ind, SCR_Group, RecordStatus, Keyword_Changed, EffectiveDate, MCP_Partition_Code, Default_Ticketing_Carrier, Station_Code, tdb_created_at)
VALUES
(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);